[build]
  functions = "lambda-build"
  command = "mkdir lambda-build && go get ./... && go build -o lambda-build/tes tes.go && npm run build"
  publish = "public"

[[redirects]]
  from = "/api/first"
  to = "/.netlify/functions/first"
